version: 2
jobs:
  bobby:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run : echo "A first hello"
  sally:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run : echo "Double check"

workflows:
    version: 2
    bobby_sally:
      jobs:
        - bobby
        - sally

